#!/usr/bin/env php
<?php

if (is_file($autoload = __DIR__ . '/vendor/autoload.php')) {
    require $autoload;
} elseif (is_file($autoload = __DIR__ . '/../../autoload.php')) {
    require $autoload;
} else {
    fwrite(STDERR,
        'You must set up the project dependencies, run the following commands:' . PHP_EOL .
        'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    exit(1);
}

use BrainMaestro\Envman\Commands\Add;
use BrainMaestro\Envman\Commands\Build;
use BrainMaestro\Envman\Commands\Encrypt;
use BrainMaestro\Envman\Commands\GenerateKey;
use BrainMaestro\Envman\Commands\Show;
use Symfony\Component\Console\Application;

$application = new Application('Envman', 'v0.1.0');

$application->add(new Add);
$application->add(new Build);
$application->add(new Encrypt);
$application->add(new GenerateKey);
$application->add(new Show);

$application->run();
